### ISSUE TITLE
Doesn't work if there is zoom style on any of the parent

### ISSUE THREAD

**Issue by johnsmathew** [CrackerakiUA/ui-cropper#13]
If there is a css zoom on any of the parents, the crop handles doesn't work. The image loads and the default crop area is also shown. But the crop area can't be changed. I am not sure if this is an issue with the library or with HTML5 canvas. The X and Y points detected from the touch event doesn't map to actual point of the crop handle, it seems.

I modified `onMouseUp`, `onMouseDown`, and `onMouseMove` and divided `pageX` and `pageY` with the css zoom value of the page. This solved the issue for me. But this is not a permanent solution because zoom can be applied to any element in the parent hierarchy and can cause an issue.

**Comment by CrackerakiUA** [comment]
Theoretically if you set css zoom via `ng-style` then you can add options for the cropper to work by your script.

**Comment by johnsmathew** [comment]
Tried setting zoom via ng-style. It doesn't work still. Is there some options I should add to ui-cropper?

**Comment by CrackerakiUA** [comment]
I mean, what you can do as option for cropper. Have one object which will have zoom option, then pull that data from css and cropper in the correct way.
