### ISSUE TITLE
Meteor Package unavailable

### ISSUE THREAD

**Issue by maxfriedmann** [CrackerakiUA/ui-cropper#16]
Not a show stopper, the npm package works just fine! But the mentioned meteor package does not exist on atmospherejs.com

**Comment by CrackerakiUA** [comment]
Yes, i was trying to add it, without success. I am not user of meteor, if you could help, that would be amazing.

**Comment by maxfriedmann** [comment]
With the full support of NPM packages I would rather not recommend adding a separate meteor package at all. I believe that this would only makes sense if you would actually use any of the meteor API. 

I would instead delete the documentation about it or replace the meteor add command with `meteor npm install --save ui-cropper` which is what I did instead.

Great rebirth of the original ngImgCrop project btw., I like this version a lot more!

**Comment by CrackerakiUA** [comment]
cool.
