### ISSUE TITLE
Uploaded image don't use all the available space when using init-max-area="true"

### ISSUE THREAD

**Issue by decko** [CrackerakiUA/ui-cropper#18]
I've been trying to use ui-cropper to crop and upload an image. To do this, I created a div to show the uploaded image and the crop tool, using the following code:

```html
<div 
    ngf-drop 
    ng-model="headerImage" 
    ngf-pattern="image/*" 
    class="cropArea"
    flex>
    <ui-cropper
        image="headerImage | ngfDataUrl"
        area-type="rectangle"
        ng-init="croppedDataUrl=''"
        aspect-ratio="2.6"
        result-image="croppedDataUrl"
        result-image-size="{w:960,h:370}"
        init-max-area="true">
    </ui-cropper>
</div>

<div>
    <img ng-src="{{croppedDataUrl}}" alt=""/>
</div>
```

But when I upload an image, the image is not using the entire space of the ui-crop area, like this:
![captura de tela de 2016-12-20 08-55-35](https://cloud.githubusercontent.com/assets/20204/21390197/c32ea254-c76c-11e6-854b-17f797ecd2f7.png)

What can it be?

**Comment by CrackerakiUA** [comment]
I am not using this feature, but from what i have seen in my tests, you have to add something in the css. In near feature i will checkup codepens and add one with this feature.

**Comment by decko** [comment]
ping

**Comment by decko** [comment]
ping

**Comment by decko** [comment]
Hey @CrackerakiUA, any codepen where we could look for a solution to this?

**Comment by CrackerakiUA** [comment]
i will try to make it this evening.

**Comment by CrackerakiUA** [comment]
Please checkup this [LINK](http://codepen.io/Crackeraki/pen/oBoepX) and leave some comments.

**Comment by pahan40** [comment]
I have the same behavior. I tried all options but no success. Canvas inside croparea is always 300 pw width and 200 px height. How could I change this ?

**Comment by Bodom78** [comment]
For some reason, width or height never seen to exceed 300px when I use this library.

**Comment by smohammedyasin** [comment]
i was having same issue. 
after i added reference of  ui-cropper.css then canvas worked perfectly.

**Comment by Bodom78** [comment]
@smohammedyasin Thanks buddy, that did the trick.

**Comment by rickerd** [comment]
Solved i guess.
