### ISSUE TITLE
Is it already stable enough?

### ISSUE THREAD

**Issue by RobbertWolfs** [CrackerakiUA/ui-cropper#2]
Because when I install this package an add it to as a dependency and add the directive to my html it won't work..

When I use the ngImgCropFullExtended package and do the same steps I does work..

Thanks in advance..

**Comment by CrackerakiUA** [comment]
Do you use the new name? You can check sample which is working normally.

**Comment by CrackerakiUA** [comment]
It's looks stable on my side, but i haven't test it properly. Also codepen has issues, so it could be that i miss something.

**Comment by RobbertWolfs** [comment]
Yes I used the new name.. 
On codepen the example worked for me. So I'll give it another shot.

If it won't work I let you know.

Thanks for the quick response :)

**Comment by RobbertWolfs** [comment]
For some kind of reason the canvas is not added when I use the ui-cropper directive..

Any ideas?

**Comment by CrackerakiUA** [comment]
How do you include it?

**Comment by RobbertWolfs** [comment]
I use 

    import 'ui-cropper/compile/unminified/ui-cropper';

Then I use 

   angular
    .module('app', [
       'uiCropper',
    ]);

And in my template (jade) I use

     ui-cropper(image="myImage" result-image="croppedImage" canvas-scalemode="true" area-type="circle")

**Comment by RobbertWolfs** [comment]
If I don't use import but just include the uicropper.js in a script tag in my html and I try it it works..

But I need to make it work inside a [https://github.com/likeastore/ngDialog](modal). When using a script tag it renders the canvas but after uploading  the canvas does not get updated and I don't see my image..

This all worked with the previous package so is there something changed ??

**Comment by CrackerakiUA** [comment]
I changed couple files. Gulp build for example, but I only change the name.

**Comment by RobbertWolfs** [comment]
Yeah I think I got it.. I was using it alongside with [an angular file uploader](https://github.com/nervgh/angular-file-upload). 

Still using it now but changed the ui-cropper image attr to another variable and now it works for some kind of reason..

Strange it worked with the previous package before.. But looks like it working now..

I'm going to test it a little bit more and let you know :)

**Comment by CrackerakiUA** [comment]
Great

**Comment by RobbertWolfs** [comment]
One thing that did not work is the 
    import 'ui-cropper/compile/unminified/ui-cropper';

Right now I just have to include it with a script tag in my html.

Is this something you can check and fix? Because I would like to import it 👍 

Thanks in advance.

**Comment by CrackerakiUA** [comment]
I am not user of webpage, don't have any experience of it. You can't see any error or something?

**Comment by RobbertWolfs** [comment]
But you made this package?

**Comment by rickerd** [comment]
@robert what packager do you use? This plug-in is made with several people including myself.
Denys uses this but not on a webpage, thats why he doesn't know this.

**Comment by RobbertWolfs** [comment]
@rickerd 

I did `npm install ui-cropper` and than I did `import '../node_modules/ui-cropper/compile/unminified/ui-cropper';`

But than it does not work for some kind of reason..

**Comment by RobbertWolfs** [comment]
Than my html is rendered as followed :

    <div class="cropArea">
        <ui-cropper class="ui-cropper--avatar" image="fullImage" result-image="croppedImage" canvas-scalemode="true" area-type="areaType" result-image-size="150" area-min-size="150"></ui-cropper>
      </div>

**Comment by RobbertWolfs** [comment]
If I use a script tag in my html 
    <script src="//rawgit.com/CrackerakiUA/ui-cropper/master/compile/unminified/ui-cropper.js"></script>

Than is my rendered html the following : 
    
    <div class="cropArea">
        <ui-cropper class="ui-cropper--avatar ng-isolate-scope true" image="fullImage" result-image="croppedImage" canvas-scalemode="true" area-type="areaType" result-image-size="150" area-min-size="150"><canvas width="300" height="197" style="margin-top: 0px;"></canvas></ui-cropper>
      </div>

**Comment by CrackerakiUA** [comment]
In which cases `import` can fail?

**Comment by RobbertWolfs** [comment]
I don't know why the import is different from the script tag.. 
Because with the ngImgCrop package it worked..

**Comment by rickerd** [comment]
The import is what i dont understand. Personally i use grunt or gulp.
Import is a module is think and i dont think the package works with that.
But its strange that the html needs to be changed.

And Denys, did you change something to the core of ui-cropper?

**Comment by CrackerakiUA** [comment]
No, just make renames.

**Comment by rickerd** [comment]
Is there something to recreate it @RobbertWolfs?
I don't see why it would **not** work.

**Comment by RobbertWolfs** [comment]
I also tried using it with require but also that does not work..

**Comment by RobbertWolfs** [comment]
Just to be sure...

This is the file I need to use, right?

https://github.com/CrackerakiUA/ui-cropper/blob/master/compile/unminified/ui-cropper.js

**Comment by CrackerakiUA** [comment]
Try also minified. And some dudes was speaking about `import '../node_modules/ui-cropper';` or `import '../node_modules/ui-cropper/index';` or `import '../node_modules/ui-cropper/index.js';`

**Comment by RobbertWolfs** [comment]
@CrackerakiUA i'll try that :)

**Comment by RobbertWolfs** [comment]
@CrackerakiUA nope, stil not working..

But there must be something changed I guess because when I try to do the following (with the previous package).. 

`import '../node_modules/ng-img-crop-full-extended/compile/unminified/ng-img-crop';` 

The canvas **does** get rendered...

**Comment by CrackerakiUA** [comment]
As far as i know people don't use compiled files with webpack, they use source code.

**Comment by RobbertWolfs** [comment]
Yeah but even with`import '../node_modules/ui-cropper/index.js';` it does work..

**Comment by CrackerakiUA** [comment]
Can you debug it?

**Comment by RobbertWolfs** [comment]
@CrackerakiUA @rickerd  ok found one problem...

when using **npm install** for some kind of reason the crop.directive is **missing**...
when using **this github url** the crop.directive is **not missing**.. 

So there is nothing wrong with import, that's a good thing. But the two versions are different...

When using this github url I still get the following error..

    ReferenceError: ColorThief is not defined

Any suggestions on that?

**Comment by CrackerakiUA** [comment]
Perhaps we need to fix package.json to tell install ColorThief on webpack.

**Comment by mariosvlad** [comment]
see [here](https://github.com/CrackerakiUA/ui-cropper/commit/7cf7b4828f932c011fd23465754b0e1c4a496262#diff-d5981bda02e661be65978cbd969c12d4) , an important part was missing from the compiled file, that's why it works using the latest file on git but not using the latest bower release, so a bower update should solve the problem (at least the initial one)

**Comment by RobbertWolfs** [comment]
@mariasvlad but I'm using npm ;)

**Comment by mariosvlad** [comment]
@RobbertWolfs a new release for both of them then :p . they are using the same [tag](https://github.com/CrackerakiUA/ui-cropper/tree/1.0.0) which has the problematic compiled files

**Comment by CrackerakiUA** [comment]
i will do one in half hour.

**Comment by CrackerakiUA** [comment]
Please test now.

**Comment by mariosvlad** [comment]
works fine here, thanks

**Comment by RobbertWolfs** [comment]
@CrackerakiUA The npm install works :) 

The only error I still get is the `ReferenceError: ColorThief is not defined`..

When I check the code, I see that ColorThief is used before it was initialised. Can this be the problem?

**Comment by RobbertWolfs** [comment]
This error occurs in the getDominantColor function of the ui-cropper..

**Comment by j-walker23** [comment]
@RobbertWolfs Just a heads up in case webpack is like `jspm`. I had to set the `ui-cropper.js` file to be loaded as `global` instead of `cjs`. That way `ColorThief` is loaded from the self executing code and will be available during the `getDominantColor` call.

I would assume there is a similar setup in webpack. Good luck.

**Comment by j-walker23** [comment]
Also @CrackerakiUA, figured you probably already knew but i'll mention it anyway. The css is still pointing to the old directive name and not `ui-cropper`.
Thanks for this lib!

**Comment by RobbertWolfs** [comment]
@j-walker23 Do you maybe have an example?

**Comment by RobbertWolfs** [comment]
@CrackerakiUA what does the getDominantColor function do? Is it always necessary to call this function?

**Comment by CrackerakiUA** [comment]
@RobbertWolfs yes, it is. In webpack you have to load it manually, something like @j-walker23 said.
@j-walker23 Thank you for the feedback, didn't saw that.

**Comment by j-walker23** [comment]
@CrackerakiUA np, glad to help.

@RobbertWolfs check out https://webpack.github.io/docs/shimming-modules.html

The part "file.js expect that this is the global context." is the concept that you are looking for. Because if you look at the `ColorThief` `iife`, you can see it passes in `this` at the bottom of the whole block. You need `this` to be `window`, instead of a normal commonjs module.

I don't have an example because `jspm` is 100% different and i don't know webpack. Sorry!

**Comment by rickerd** [comment]
Is this issue still accurate? The package does work now i guess since all the name changes were done.

**Comment by RobbertWolfs** [comment]
@rickerd The package works with npm install now but still get the error of ColorThief..

**Comment by rickerd** [comment]
Okay, that's weird. Can we discuss this on [Gitter?](https://gitter.im/CrackerakiUA/ui-cropper?utm_source=share-link&utm_medium=link&utm_campaign=share-link)
So we can solve your issue and have a more stable package.

**Comment by RobbertWolfs** [comment]
@rickerd 👍

**Comment by SamarRizvi** [comment]
Any resolution for ColorThief error

**Comment by RobbertWolfs** [comment]
@SamarRizvi Not yet

**Comment by j-walker23** [comment]
@SamarRizvi Are you using a module loader? If you are then you just need to shim `ui-cropper` as a global. Its been working for me for the last week once shimmed.

**Comment by mvill** [comment]
To fix "ColorThief is not defined" error, use : 
`require('imports?this=>window,exports=>false,define=>false!ui-cropper');`
instead of : 
`require('ui-cropper');`

This worked for me.


in ui-cropper, there's this piece of code : 
`    /**`
`     * Export class to global`
`     */`
`    if (typeof define === 'function' && define.amd) { //block 1`
`        define([], function() {`
`            return ColorThief;`
`        }); // for AMD loader`
`    } else if (typeof exports === 'object') {`
`        module.exports = ColorThief; // for CommonJS //block 2`
`    } else {`
`        this.ColorThief = ColorThief; //block 3`
`    }`

"require('ui-cropper');" pass in block 1
"require('imports?define=>false!ui-cropper');" pass in block 2
"require('imports?exports=>false,define=>false!ui-cropper');" pass in block 3
"require('imports?this=>window,exports=>false,define=>false!ui-cropper');" makes the "this" var to point on window (global)

**Comment by rickerd** [comment]
Can you make a PR for this improvement.
Also maybe add something to the wiki so everybody can look at your fix.

**Comment by yaoyonstudio** [comment]
@mvill is right.

require('imports?this=>window,exports=>false,define=>false!ui-cropper');
instead of :
require('ui-cropper');

and problem solved.

oh, don't forget install  imports-loader first.
npm install  imports-loader --save-dev

Thanks, @mvill . big help!
