### ISSUE TITLE
How to upload the cropped image

### ISSUE THREAD

**Issue by RenukaMP** [CrackerakiUA/ui-cropper#24]
I have used your crop code in my project, cropping image is showing fine. But how to upload the cropped image via api?

How to pass crop image  in form ?
Please help!

**Comment by CrackerakiUA** [comment]
You have dataUrl result which you can use as you like. You can make blob and upload it as file or you can upload dataUrl directly.

**Comment by fr4nkfurt** [comment]
hi, having the same problem here...
HTML: 
<ui-cropper area-type="square" image="objectValue.base64uploadedimage" result-image="myCroppedImage" result-blob="myCroppedImageblob" url-blob="myCroppedImageUrlBlob"></ui-cropper>

Controller:
						$http.post('imgservice?type=img', {
							fileBase64DataUrl : $scope.myCroppedImage,
							fileBase64DataUrla : $scope.myCroppedImageblob,
							fileBase64DataUrlb : $scope.myCroppedImageUrlBlob...

All three are having null / undefined values.
Am I doing something wrong? As mentioned by Renuka, I am also able to see the cropped image by using <img ng-src="{{myCroppedImage}}" /> on my HTML.

Thanks!

**Comment by fr4nkfurt** [comment]
Hi again,

Seems my problem was not following the demos provided.
I was able to fix this by:

HTML:
Added live-view directive to ui-croper:
`live-view="blockingObject"`
Controller:
`    $scope.blockingObject = {block:true};
`
AND
`
 $scope.blockingObject.render(function(dataURL){
						     $scope.test=    dataURL;
						      });
`
AND
`
$http.post('TransformImage?type=img', {
							fileBase64DataUrl : $scope.test,
`

**Comment by smohammedyasin** [comment]
Hello, 
for me 
`$scope.blockingObject.render(function(dataURL){ $scope.test= dataURL; });` not working.
i'm getting "**TypeError: $scope.blockingObject.render is not a function**"
