### ISSUE TITLE
Demo's outdated and not working with new version

### ISSUE THREAD

**Issue by Fossil01** [CrackerakiUA/ui-cropper#25]
The demo's still use the old ngImgCropper. I edited one to include the new files and module name but it doesnt work.

Any idea why? @CrackerakiUA 

http://codepen.io/anon/pen/dNNweQ

**Comment by CrackerakiUA** [comment]
i had that issue also, that why i didn't create codepens for ui-cropper. Didn't had the time to investigate this issue.

**Comment by Fossil01** [comment]
Ok. Will use the old version for now. How do I get a crop selection which is rectangle but vertical?

aspect-ratio="1.7"  is horizontal.
