### ISSUE TITLE
result-image-format not working after upgrading from ng-img-crop to ui-cropper

### ISSUE THREAD

**Issue by svencowart** [CrackerakiUA/ui-cropper#26]
Previously the data-uri in "result-image" would start with "data:image/jpeg..." but after upgrading the library to ui-cropper the data-uri in "result-image" starts with "data:image/png...", even though I have set "result-image-format='image/jpeg'".

Here is how I am declaring the directive attributes:
`<ui-cropper area-type="square" image="$ctrl.avatar.original" result-image="$ctrl.avatar.cropped" result-image-format="image/jpeg" result-image-size="240"></ui-cropper>`

**Comment by CrackerakiUA** [comment]
Will checkup this tomorrow

**Comment by jnd-noggin** [comment]
Just ran into this issue too.
As a quick fix, you can do: `result-image-format="'image/jpeg'"`
In terms of fixing the bug, need to change the binding for result-image-format to `@`.

**Comment by svencowart** [comment]
@CrackerakiUA I went in and fixed the problem with @jnd-noggin suggestion.  I tested the solution and it does indeed work.  First time committing to an open-source project. Hopefully I did everything right, there should be a pull request ready to be merged.
