### ISSUE TITLE
New feature:  ellipse crop

### ISSUE THREAD

**Issue by astw** [CrackerakiUA/ui-cropper#29]
I don't know where to put this, so I just write here. 

I'd like to see this directive be able to crop an image into an ellipse shap.

Thanks

**Comment by CrackerakiUA** [comment]
ellipse will have rectangle as result, but yes, we can support this. But still, very few cases need it, i don't remember any that i needed it.

**Comment by rickerd** [comment]
As of the plugin being Open Source the best way to tackle your request is to build it yourself @astw 
That's what i also been doing when i needed features.

**Comment by CrackerakiUA** [comment]
Yes, mostly enhancements are coming from people which need them. No one get payed to build things which they don't need :)

**Comment by astw** [comment]
Well fair enough.  Thanks.

**Comment by rickerd** [comment]
Closing the issue since no interaction has been done.
If you want the feature, build it and share it with us.
