### ISSUE TITLE
Adding transparent when not giving any aspect ratio

### ISSUE THREAD

**Issue by ishaq-bhojani** [CrackerakiUA/ui-cropper#32]
Actually I was trying to let user crop how he needs to, without any size restriction
cropper is working but I can't get image's size what user cropped, instead of this, it is adding a transparent part to maintain height and width and making an Image of 200 by 200 PX that it by default uses as written in API, take a look at the Screen shot

![screen shot 2017-02-15 at 12 40 07 pm](https://cloud.githubusercontent.com/assets/9676689/22964735/ef3159f6-f37b-11e6-846e-6260026322e4.png)

Please add this feature

**Comment by cjy37** [comment]
+1

**Comment by rickerd** [comment]
If you want this feature... it's OpenSource software so go ahead and help yourself.
@CrackerakiUA isn't able to do it all on his own.
When i needed features back then i also implemented them myself helping the plugin and myself.

**Comment by rickerd** [comment]
After all these months no progress. Closing this issue.
