### ISSUE TITLE
area rectangle ratio

### ISSUE THREAD

**Issue by pixedd** [CrackerakiUA/ui-cropper#35]
Hi, I would like to set the default area to 270*70px, here is my settings:

`<ui-cropper image="myImage" area-type="rectangle" aspect-ratio="3.85" result-image="myCroppedImage" result-image-size='{w: 270,h: 70}' area-init-size='{w: 270,h: 70}' init-max-area="true"></ui-cropper>`

When I upload a png with that ratio (270x70), the canvas size is 385x100, is it possible to import my image in a crop area of max 270x70 ?

Thanks !

**Comment by CrackerakiUA** [comment]
export dataUrl is not at max up to 270*70?

**Comment by pixedd** [comment]
@CrackerakiUA what do you mean ?

Here is a screenshot of the result:
<img width="840" alt="capture d ecran 2017-03-20 a 12 40 42" src="https://cloud.githubusercontent.com/assets/4927979/24098404/8c5cb97a-0d6a-11e7-9154-a58538dcfc4e.png">

I would like my canvas to have an area init size of 270 x 70 as specified and not 385 x 100

**Comment by CrackerakiUA** [comment]
So your project is that canvas it self has bigger size? If result image is correct. Or did i get you wrong?

**Comment by pixedd** [comment]
Here is a use case, I warn my user to upload an img of 270 x 70, when he is uploading is image the peview (canvas) is 385 x 100 instead of 270 x 70. The result image is good (270 x 70) but it might be confusing to have a preview (canvas) with a different size and a pixelised image.

I would like to have a canvas of 270 x 70px, like that if the user upload a 270x70 image he will not be able to crop it (because of min-size...), however if the user upload a bigger image he will then be able to crop it to 270 x 70

**Comment by CrackerakiUA** [comment]
Sounds crazy :)
keep your canvas as big as you can to work nicely, and have your result image as you wish.
Besides if you really want to have what you are asking, use your css.
