### ISSUE TITLE
Crop an area larger than the box

### ISSUE THREAD

**Issue by hschaffer22** [CrackerakiUA/ui-cropper#36]
I want to crop to an area larger than the adjustable crop area.  I don't want to make the crop area larger, because I'm going to be showing the image at different widths (same height), and I want the user to size the image for the smallest possible width that will be shown.

Basically, I need the dashed adjustable area to be smaller (and a different aspect ratio) than the crop area.  Where do I need to adjust the code to make that happen?

**Comment by rickerd** [comment]
This is done by JavaScript and rendered in a canvas element.
If you can make it adjustable... it would be great because then it will be awesome if you can choose different versions of the dotted or dashed line.
And also the height and stuff what you want.

**Comment by rickerd** [comment]
No response, closing issue.
