### ISSUE TITLE
White lines appearing on cropped img

### ISSUE THREAD

**Issue by Freego1783** [CrackerakiUA/ui-cropper#38]
Hey,

Sometimes i get some white lines , either horizontal or vertical ones, on my cropped img. Can't really say how i manage to get these, it seems kinda random.

Any ideas how to get rid of those ?

![white lines](https://cloud.githubusercontent.com/assets/4101360/24743355/33fc2f12-1aae-11e7-8482-26acb5ed97d1.PNG)

**Comment by rickerd** [comment]
This is a well known issue. Sadly the bug cannot be found.
If you're willing to do a bug-hunt, please do!

**Comment by CrackerakiUA** [comment]
We are solving it with a cute trick. Before we add image to cropper, we resize it up to for examxple 1920*1080. This make cropper work smoother and you have no white lines.

**Comment by Freego1783** [comment]
Okay thanks, i'll give it a try !

**Comment by rickerd** [comment]
> We are solving it with a cute trick. Before we add image to cropper, we resize it up to for examxple 1920*1080. This make cropper work smoother and you have no white lines.

Can we make a Wiki page of this @CrackerakiUA ?
In the future we won't have users creating this issue again.
