### ISSUE TITLE
Resize Coordinates Position

### ISSUE THREAD

**Issue by a2tes** [CrackerakiUA/ui-cropper#4]
Hello Honchar,
I know little English. So, I've a problem associated with this plugin. I use your cropper plugin in my AngularJS Project. But resize coordinates doesn't work. Resize coordinates and mouse coordinates looks different from each other when resizing. How to fix this problem? 
I'm using AngularJS v1.3.7 and Bootstrap v3.3.5

![photo_2016-10-30_16-28-31](https://cloud.githubusercontent.com/assets/23128112/19836867/a5881f76-9eb5-11e6-9608-cc0d98932c3b.jpg)
![photo_2016-10-30_16-28-47](https://cloud.githubusercontent.com/assets/23128112/19836868/a5904ebc-9eb5-11e6-9024-25d38edbed86.jpg)

**Comment by CrackerakiUA** [comment]
Please start with codepen link of your options and the scenario which you try to do.

**Comment by a2tes** [comment]
Your plugin is running on Codepen. But it doesn't work on my project. It gives the following warning in the console display: **This plugin is deprecated in the name of the u-cropper. You can find it under the https://github.com/crackerakiua/ui-cropp**. Maybe this warning can help you for fix my problem.

**Comment by CrackerakiUA** [comment]
Strange, this log is from our previous plugin page.

**Comment by CrackerakiUA** [comment]
Are you sure you are not using this one? 
https://github.com/CrackerakiUA/ngImgCropFullExtended

**Comment by CrackerakiUA** [comment]
And if your scenario is running on codepen, uselly it's something with your angular code.

**Comment by a2tes** [comment]
@CrackerakiUA Thank you for your help. ngImgCropFullExtended is running.

**Comment by rickerd** [comment]
You should use this ui-cropper version. The other one is deprecated.
