### ISSUE TITLE
Unable to un-set aspect-ratio after it has been set

### ISSUE THREAD

**Issue by jjoekoullas** [CrackerakiUA/ui-cropper#41]
I need to be able to switch, on the fly, between cropping to an aspect ratio and cropping to any size.

After an aspect ratio has been specified, it cannot be removed (only replaced).

Steps to reproduce:
1. Specify an aspect ratio
2. Specify an aspect ratio of null
Expected results:
Cropping loop is no longer locked to aspect ratio
Actual results:
Cropping loop is locked to aspect ratio

It looks like the line which causes this is: https://github.com/CrackerakiUA/ui-cropper/blob/master/source/js/ui-cropper.js#L294
Likely https://github.com/CrackerakiUA/ui-cropper/blob/master/source/js/classes/crop-host.js#L844 would need to be modified to support un-setting an aspect ratio in the case when it gets passed null.

**Comment by rickerd** [comment]
Make a PR and will merge it. You would help the library alot.

**Comment by nadar** [comment]
Same issue here. Any work around suggestions? :/

**Comment by CrackerakiUA** [comment]
> Same issue here. Any work around suggestions? :/

Sorry, maintain time for this plugin is tiny

**Comment by nadar** [comment]
Sure, i total understand that. If you give me a hint, i will send you a PR - cause this ui-cropper library is still insanely perfect!

**Comment by CrackerakiUA** [comment]
You can easily create refresh effect with `ng-if`. 
If you would like to create fix for that, you will need to add else here: https://github.com/CrackerakiUA/ui-cropper/blob/master/source/js/ui-cropper.js#L313

**Comment by nadar** [comment]
@CrackerakiUA yes `ng-if` works in combination with `$timeout()` :+1:
