### ISSUE TITLE
Hi, I want to set size for crop-area and disable it for user, and user just move the crop-area. How can I achieve this? Thanks

### ISSUE THREAD

**Issue by shamimafridi** [CrackerakiUA/ui-cropper#42]
Hi,
I want to set size for crop-area and disable it for user, and user just move the crop-area.
How can I achieve this?
Thanks

**Comment by rickerd** [comment]
You can see all the options on this page https://github.com/CrackerakiUA/ui-cropper/wiki/Options
But you'll need something like
     
       area-min-size="{ number|{w:100,h:100} }"
       allow-crop-resize-on-corners="false"

**Comment by shamimafridi** [comment]
Thanks @rickerd  but i am still facing the issue. not succeed to disable the cropper size

**Comment by rickerd** [comment]
If it's not working it has not been implemented before.
If you want this feature, build it and share it with us please.

We don't make any profit on this project and all features that are in the cropper now has been implemented by ourselves because we needed it just like you do right now.
