### ISSUE TITLE
Aspect ratio not working on IE11

### ISSUE THREAD

**Issue by vincaslt** [CrackerakiUA/ui-cropper#5]
In IE11 on windows 7, I'm trying to set fixed aspect ratio, but it acts weird, and if console is open, it's throws IndexSizeError.

Example can be seen here: http://codepen.io/anon/pen/amgXPg

**Comment by sdeprez** [comment]
I can confirm the same `IndexSizeError` with this directive (in jade, but that's the idea):
```
ui-cropper(
  area-min-size="{w: 500, h: 166.67}",
  area-type="rectangle",
  aspect-ratio="3",
  canvas-scalemode="full-width",
 cropject="picture.cropInfo",
 image="picture",
 result-blob="picture.croppedBlob",
 result-image="picture.croppedImage",
 result-image-format="'image/jpeg'",
 result-image-quality="1.0",
 result-image-size="'max'",
)
```
The error happens when I first upload a picture that is too small compared to the required `area-min-size` and it may be related to negative width and height (at least there are negative values in the `cropject`. See there?
http://stackoverflow.com/questions/19338032/canvas-indexsizeerror-index-or-size-is-negative-or-greater-than-the-allowed-a

Anyway, thanks for your amazing library!

**Comment by oliversalzburg** [comment]
The error is thrown on https://github.com/CrackerakiUA/ui-cropper/blob/9681aa47dadcd3a941ffb9fb7651e193d12b1119/source/js/classes/crop-canvas.js#L187

**Comment by oliversalzburg** [comment]
@rickerd Was this fixed?

**Comment by rickerd** [comment]
No but the issue has not been touched for several months.

**Comment by oliversalzburg** [comment]
I guess this also implies that the issue won't be fixed unless I (or someone else) fix it myself? :D

**Comment by rickerd** [comment]
Sorry i'm not paid for this project so everything i did i needed myself.
So yes, please fix the issue if you have trouble with it.

**Comment by Axel186** [comment]
I had the same issue on Edge browser. As @sdeprez said, the problematic situation is when you try to crop small image.

In my example I used `aspect-ratio="3"` and my image size was: `200x300`.
As I understood later `area-min-size` set to `{w: 80, h: 80}` by default. So if I use ratio 3:1, my min-width of image should be 240px - here is the conflict!

The solution is pretty simple, I set my `area-min-size` to `{w: 1, h: 1}`

**Comment by CrackerakiUA** [comment]
can you tell me in which case you would allow to crop small images?

**Comment by Axel186** [comment]
@CrackerakiUA , you absolutely right! This might sound funny, but in my situation, I had the image which is less than 240px width. 

The image was portrait (240x600, not sure) and it was impossible to crop this image. This might be an avatar or something else.

Can't remember the details right now, but I used the tricky solution above.

**Comment by CrackerakiUA** [comment]
Sounds like logical solutions, but i do agree that it's not simple to think about that solution.

**Comment by CrackerakiUA** [comment]
I never had case like this before :)
