### ISSUE TITLE
npm release

### ISSUE THREAD

**Issue by AdriVanHoudt** [CrackerakiUA/ui-cropper#51]
Any chance on a new npm release?

**Comment by rickerd** [comment]
@CrackerakiUA can we make a new version? It seems that a minor version is needed due to the Webpack fix.

**Comment by CrackerakiUA** [comment]
ok, sure.

**Comment by CrackerakiUA** [comment]
@AdriVanHoudt i have made publish, @1.0.5
please verify that everything is ok, as i didn't make compile bcs i don't have ruby installed on this environment.

**Comment by AdriVanHoudt** [comment]
@CrackerakiUA nice 🎉 
I opened a PR where I ran `gulp` and `gulp build` for you https://github.com/CrackerakiUA/ui-cropper/pull/52

If you want I can do some more work like updating deps and removing the ruby dependency if you'd like

**Comment by CrackerakiUA** [comment]
Any positive work is welcome, i have Ruby on my personal environment, when i am working on plugin. Any way i never understood why Ruby is needed, sass can be used with sass-middleware, this was made by Author of the cropper.

**Comment by CrackerakiUA** [comment]
ui-cropper@1.0.6 published

**Comment by AdriVanHoudt** [comment]
@CrackerakiUA awesome thanks, it seems like you didn't push the version changes to github yet?

**Comment by CrackerakiUA** [comment]
Fixed.

**Comment by spiralx** [comment]
Could you also update Bower please? It's currently still on 1.0.4. Thanks.

**Comment by rickerd** [comment]
Isn’t it that bower searches for the latest version?
If you look at the bower.json there’s no version present.

**Comment by CrackerakiUA** [comment]
I guess it's checking releases, i will make new one.

**Comment by CrackerakiUA** [comment]
1.0.6 release is out.

**Comment by AdriVanHoudt** [comment]
afaik this issue now definitely closed ;)
