### ISSUE TITLE
"Init Url Crop" demo doesn't work with other pictures

### ISSUE THREAD

**Issue by elias-identos** [CrackerakiUA/ui-cropper#54]
Hi there!

The _Init Url Crop_ demo on [codepen](https://codepen.io/Crackeraki/pen/QjmNVM) seems to be broken in some way.

When I change the init url to 
`$scope.myImage = 'http://www.planwallpaper.com/static/images/i-should-buy-a-boat.jpg';` the image is no longer loaded.

This error seems to occur with other pictures as well.

Thanks for your help!

**Comment by CrackerakiUA** [comment]
My default image is loading, your service is not blocking codepen?

**Comment by elias-identos** [comment]
I don't have control about the _planwallpaper_ site - the URL was just an example.

This behaviour also occurs for several other URLs, e.g. [](https://service.wallin-app.com/images/ce41.jpg), [](https://cdn.pixabay.com/photo/2017/01/08/13/58/cube-1963036_1280.jpg), [](http://www.publicdomainpictures.net/pictures/30000/velka/beauty-of-nature-17.jpg)

On the other side some pictures just work as intended - i just can't figure out the difference.

**Comment by elias-identos** [comment]
Ahh, I should have debugged with Chrome all the time. Unlike the Firefox console, Chrome clearly states that the issue is caused by the CORS policy:

> Access to Image at 'http://www.publicdomainpictures.net/pictures/30000/velka/beauty-of-nature-17.jpg' from origin 'https://s.codepen.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://s.codepen.io' is therefore not allowed access.

Excuse me for consuming your time!

**Comment by CrackerakiUA** [comment]
:D
