### ISSUE TITLE
Possible to set areaCoords? 

### ISSUE THREAD

**Issue by mosspaper** [CrackerakiUA/ui-cropper#58]
Is there a way to _set_ the areaCoords onto a loaded image based on values for x, y, w, & h? 

Currently, I can get the areaCoords values to be saved in the DB. When the user reloads the image, the cropped area should be preserved and want to set the same areaCoords from before.

I was not able to figure out how to do this in the current release.

**Comment by CrackerakiUA** [comment]
https://codepen.io/Crackeraki/pen/YqKwzZ
check this out.

**Comment by mosspaper** [comment]
Thanks for responding so quickly and for your awesome work on this project! I did have a look at the codepen, but I wasn't able to update the cropTop & cropLeft values. Only cropWidth & cropHeight work. Please advise

**Comment by CrackerakiUA** [comment]
I don't remmeber if we can update those, need to looks at code, will try to do that in few days. You can also can have a look

**Comment by mosspaper** [comment]
Will definitely take a look at the code as well. Thanks!

**Comment by mosspaper** [comment]
So I was able to figure this out by setting the area coords (x, y, w, h) through **area-init-coords**.

**Comment by briansanchez** [comment]
this is finally working.. thank you @CrackerakiUA for all the hard work on this angularjs cropper.

`<ui-cropper image="imageSrc" area-init-coords = "{x: 2108, y: 1805}" area-init-size = " {w: 835, h: 835}" area-init-is-relative-to-image = "true" result-image="my_account.photo_thumb" area-type="circle" area-coords = "myCoords" result-image-size="resImgSize" cropject="cropper"></ui-cropper>`

where area-init-coords is x1 and y1    and  area-init-size is the difference between w = x2-x1 and h = y2 - y1

I spent a few hours on this, I hope this can save time for someone.

**Comment by fspider** [comment]
@briansanchez  Thanks. You saved my time !!!
