### ISSUE TITLE
How to fix only width on result image?

### ISSUE THREAD

**Issue by vincaslt** [CrackerakiUA/ui-cropper#6]
I would like to get a result image with dimensions 1024 x Y.
Using `result-image-size` I can fix both dimensions, but I would like to allow resizing of the crop area, while always resizing the image to 1024px width and maintaining aspect ratio.

**Comment by thierryskoda** [comment]
@vincaslt Have you found how to do it ?

**Comment by CrackerakiUA** [comment]
I believe this is not possible. I guess he have changed what he was needed. You can success this on back-end with ImageMagick.

**Comment by thierryskoda** [comment]
Oh yes true! Thanks @CrackerakiUA

**Comment by CrackerakiUA** [comment]
Generally we should have this option, i don't remember why it's not added.

**Comment by vincaslt** [comment]
Yes I could. I needed this functionality for a project at my work I no longer work at :D
It was not possible out of the box, but I just extended some calculations to fit what I needed. I basically added an option to specify 0 height or width, and in that case force aspect ratio.
