### ISSUE TITLE
Undocumented feature - "canvas-scalemode"

### ISSUE THREAD

**Issue by virtual-marat** [CrackerakiUA/ui-cropper#60]
I am find undocumented feature - "canvas-scalemode". Write about her in wiki-page :wink:

**Comment by CrackerakiUA** [comment]
Please, share your vision.

**Comment by virtual-marat** [comment]
My English is very bad, but i am found desription here:
[https://github.com/CrackerakiUA/ngImgCropFullExtended/wiki/Options#canvas-scalemode](url)

> Optional Default value is 'fixed-height'. If set to 'full-width' the directive uses all width available and the canvas expands in height as much as it need to maintain the aspect ratio. If set to 'fixed-height', the directive is restricted by a parent element in height

**Comment by CrackerakiUA** [comment]
Done, wiki updated. Thank you
