### ISSUE TITLE
Optional result-image

### ISSUE THREAD

**Issue by autowp** [CrackerakiUA/ui-cropper#63]
In my application just need to pick crop coordinates, `result-image` is useless but required by directive.

**Comment by CrackerakiUA** [comment]
there is option for that, check wiki.

**Comment by autowp** [comment]
Can't found

**Comment by CrackerakiUA** [comment]
Have you checked all codepens?

**Comment by autowp** [comment]
Are you talking about `live-view="blockingObject"` example?

Looking for something like 
```html
<ui-cropper image="myImage" cropject="cropper"></ui-cropper>
```

**Comment by CrackerakiUA** [comment]
yes

**Comment by josduj** [comment]
It works with `live-view` but i still get this error
```
Expression 'undefined' in attribute 'resultImage' used with directive 'uiCropper' is non-assignable!
```

Possibility to use `on-change` without setting `result-image` would also be nice

**Comment by CrackerakiUA** [comment]
add ```result-image="jank"``` , and i believe there wont be issue. ```on-change``` would be same heavy as result-image.
