### ISSUE TITLE
size of cropped image

### ISSUE THREAD

**Issue by xileftenurb** [CrackerakiUA/ui-cropper#68]
Hi,

I recently realized the image I saved after being cropped by the cropper are larger in size (in mb) than before, event if they are smaller in height and width.

I must keep the size of my image as low as possible for best downloading speed of my website,
somebody know how is it possible and if there is a way to fix it?

**Comment by CrackerakiUA** [comment]
Use image magic

**Comment by CrackerakiUA** [comment]
To be honest, i never tested result of the cropper in quality, as that is something that canvas provide and we can't modify. The best solution is the [Imagemagick](https://www.imagemagick.org/script/index.php) on the back-end, which provide you many things besides what you need.

**Comment by xileftenurb** [comment]
thank you,

I juste found out the difference in size come from the conversion from jpeg to png.
with imagemagick, I will be able to re-convert them back to jpeg

**Comment by CrackerakiUA** [comment]
Cropper has option for export format.
