### ISSUE TITLE
Webjars packaging

### ISSUE THREAD

**Issue by bakhlov** [CrackerakiUA/ui-cropper#7]
Can you package this library in the Webjars format?

**Comment by CrackerakiUA** [comment]
What is Webjars?

**Comment by bakhlov** [comment]
You can find more information by the link http://www.webjars.org.

**Comment by rickerd** [comment]
We dont support them.
Nowadays there are so many tools that we cannot support them all.
If you want to add a funxtionality that you use you are free to add them in a merge request.

At least thats how i think about it. We do want to help if you need some things to be done of course.

**Comment by bakhlov** [comment]
Ok, let's postpone it for the better time
