### ISSUE TITLE
Bitdepth and resolution

### ISSUE THREAD

**Issue by molnargabor** [CrackerakiUA/ui-cropper#71]
Hi!

Is it possible to set bitdepth and resolution of the cropped image? 
It always converts my images to 32 bit color and 96 dpi. This increases filesize.

Thank you!
Br.
Gábor

**Comment by CrackerakiUA** [comment]
No, as far as i remember.

**Comment by CrackerakiUA** [comment]
DPI, you can use bigger resolution to increase dpi.

**Comment by molnargabor** [comment]
Thank you, but I would be happy with 72 dpi and 24 bit color, I don't need higher resolution. :)
