### ISSUE TITLE
CORS problems

### ISSUE THREAD

**Issue by franklindner** [CrackerakiUA/ui-cropper#73]
I just tried to update from imgCrop to this newer version but the resulting images cause CORS problems when trying to upload them to my API which has CORS enabled for all endpoints and works flawlessly with result images from the old library.

Not sure what the origin of this could be, but I want to migrate to this newer version since it solves a small problem that I have with the old one where sometimes it generates 1px wide black bar on the right sight on the resulting image.

Any ideas?

**Comment by alejandro-heredia-coderoad-com** [comment]
Yes, I'm experiencing the same problem. My server-side CORS middleware works perfectly as well, but when loading the image placeholder into the cropper it just gives a CORS error. Very rare.

**Comment by CrackerakiUA** [comment]
and previous version don't have this issue?

**Comment by askmsd07** [comment]
I am also facing the CORS issue.

**No 'Access-Control-Allow-Origin' header is present on the requested resource.**

need your help.

**Comment by CrackerakiUA** [comment]
You probably use different back-end from front-end and use different domains or use ip. Add crossorigin.

**Comment by askmsd07** [comment]
I am getting the image from a s3 bucket and i have also configured the CORS for the bucket.
It was working fine while loading the image for the first time.

If i do empty catch and hard reload, then this problem is occurring.

**Comment by CrackerakiUA** [comment]
try to reset CORS also, from your comments it feels like you lose that.

**Comment by askmsd07** [comment]
I just tried, it's not resolving the problem.

Adding some more information.

The below is CORS config of the s3 bucket.

`<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
<CORSRule>
    <AllowedOrigin>*</AllowedOrigin>
    <AllowedMethod>GET</AllowedMethod>
    <AllowedMethod>HEAD</AllowedMethod>
    <MaxAgeSeconds>3000</MaxAgeSeconds>
    <AllowedHeader>*</AllowedHeader>
</CORSRule>
</CORSConfiguration>`

and this is the image url, i was trying to read from the bucket.
**https://assets-ops-dev.s3.amazonaws.com/0eaab91ef92a40eb2fd34d7129ae131c/JQM5AFMN.jpg**

**Comment by rickerd** [comment]
CORS is not a problem of the cropper.
It's a problem of the server serving the image. The cropper is hosted on a certain domain that is not trusted or similar as the resource where the image is hosted on.

We can't help this what so ever.
