### ISSUE TITLE
IE10 & IE11 InvalidStateError

### ISSUE THREAD

**Issue by sdeprez** [CrackerakiUA/ui-cropper#9]
This is a follow up of this question: https://github.com/CrackerakiUA/ngImgCropFullExtended/issues/183

I confirm the same issue with IE10 and IE11 (on windows 7), on [the same line](https://github.com/CrackerakiUA/ui-cropper/blob/master/compile/unminified/ui-cropper.js#L1722). Setting the response type *after* opening the request seems to fix the issue. More informations on this problem:

http://stackoverflow.com/questions/20760635/why-does-setting-xmlhttprequest-responsetype-before-calling-open-throw
https://connect.microsoft.com/IE/feedback/details/795580/ie11-xmlhttprequest-incorrectly-throws-invalidstateerror-when-setting-responsetype

**Comment by CrackerakiUA** [comment]
Can you make PR?
