### ISSUE TITLE
how to reset ui cropper after add image and edit image .  first image show when i add new image in canvas.  

### ISSUE THREAD

**Issue by khushmohammad** [CrackerakiUA/ui-cropper#91]
<div class="cropArea">
              
                <ui-cropper image="myImage" area-type="rectangle"  result-image="myCroppedImage" result-image-size='[{w: 200,h: 200},{w: 300,h: 300}]' result-array-image='myArray'></ui-cropper>
            </div>

**Comment by CrackerakiUA** [comment]
```
<div ng-if="refresh"></div>
```

**Comment by khushmohammad** [comment]
i was use cropper in bootstrap model . can you give me answer according to model .
this is not working.

working on your side . show me how to you put in your code.


please sir help

**Comment by CrackerakiUA** [comment]
sorry, I am not working with bootstrap

**Comment by khushmohammad** [comment]
i have done

thanks sir
