### ISSUE TITLE
Set default position of the cropper.

### ISSUE THREAD

**Issue by dipti-agrawal** [CrackerakiUA/ui-cropper#93]
I need to have the ability to set a default position of the cropper on page load.
I tried to set the positions in the cropper object but it is not overriding the default position of the cropper.
Here is what I tried:
$scope.cropper = {
        "canvasSize": { "w": 500, "h": 350 },
        "areaCoords": { "x": 0, "y": 0, "w": 500, "h": 350 },
        cropWidth: 118,
        cropHeight: 179,
        cropTop: 0,
        cropLeft: 0,
        cropImageWidth: 500,
        cropImageHeight: 767,
        cropImageTop: 0,
        cropImageLeft: 0
    };
Can you tell me how can I achieve this?

**Comment by fspider** [comment]
@dipti-agrawal  Did you solve this problem?
I also faced the same problem.
