### ISSUE TITLE
Can you crop animated GIFs using this library?

### ISSUE THREAD

**Issue by adeopura4** [CrackerakiUA/ui-cropper#95]
Can you crop animated GIFs using this library. It seems to convert the GIF image to PNG while cropping. Is there some way or some option to crop an animated GIF while keeping the animation using this library?

**Comment by rickerd** [comment]
No, this is nog possible.
Only jpg and png.

**Comment by adeopura4** [comment]
Thank you. When I try to crop an animated gif using this library, I see a "base image". I am wondering what frame of the GIF does the library pick up for the "base image"?
